### ISSUE TITLE
file digest blows up when trying to precompile assets

### ISSUE THREAD

**Issue by mustmodify** [marcandre/packable#3]
[digest.rb:46](https://github.com/ruby/ruby/blob/ca6b174078fa15f33655be704d9409fdbc4f9929/ext/digest/lib/digest.rb#L51)

how does it get from that line to read_with_packing?

```
production@server:~/app/releases/failing-release$ bundle exec rake RAILS_ENV=production RAILS_GROUPS=assets assets:precompile --trace
...
** Invoke tmp:cache:clear (first_time)
** Execute tmp:cache:clear
** Execute assets:precompile:primary
rake aborted!
TypeError: Expected a class or symbol: 16384
/home/production/app/shared/bundle/ruby/1.9.1/gems/packable-1.3.6/lib/packable/packers.rb:56:in `to_class_option_list'
/home/production/app/shared/bundle/ruby/1.9.1/gems/packable-1.3.6/lib/packable/extensions/io.rb:67:in `read_with_packing'
/usr/local/lib/ruby/1.9.1/digest.rb:46:in `block in file'
/usr/local/lib/ruby/1.9.1/digest.rb:44:in `open'
/usr/local/lib/ruby/1.9.1/digest.rb:44:in `file'
/home/production/app/shared/bundle/ruby/1.9.1/gems/sprockets-2.2.3/lib/sprockets/base.rb:133:in `file_digest'
```

**Comment by mustmodify** [comment]
After further digging, here's what I'm seeing.

http://ruby-doc.org/core-1.9.3/IO.html#method-i-read says IO#read should accept a length and a buffer. However, https://github.com/marcandre/packable/blob/master/lib/packable/extensions/io.rb#L66 suggests that the first argument can be a number, but in that case, doesn't allow for a buffer.

**Comment by marcandre** [comment]
If still a problem for you, would you mind reopening this with the current maintained repo? https://github.com/SciRuby/packable
Thanks
