### ISSUE TITLE
Test gem with ruby 2.3

### ISSUE THREAD

**Issue by v0dro** [marcandre/packable#4]

**Comment by marcandre** [comment]
PR welcome.
This library is not evolving anymore. I will accept well written PRs but will not resolve any issues as I have other priorities.
Thanks

**Comment by v0dro** [comment]
OK so SciRuby uses packable for a variety of uses.

Could you transfer ownership to me on rubygems? I'll fork it under SciRuby. My user name @v0dro and email is sameer.deshmukh93@gmail.com.

**Comment by marcandre** [comment]
Glad to hear that.

I've added you to the owner list.

**Comment by v0dro** [comment]
Could add a link to your repo stating that the gem will be maintained at SciRuby now?

Here: https://github.com/SciRuby/packable

**Comment by marcandre** [comment]
Done :+1:
